### ISSUE TITLE
Feature: User can view confirmation page

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/Delights-by-Daisy#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Use will be able to view confirmation page after successfully paying for their order.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After a successful payment, the user is directed to the confirmation page, where they can see the details of their order.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/202326225-ded6df57-4b93-4668-bc52-74fbf1a95e43.png)
![image](https://user-images.githubusercontent.com/103452411/202326329-03746eaf-7f22-4649-8a7f-f78d1edee0f1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks
- [x] Update `server/index.js` to send post request
  - [x] get cartId with token 
  - [x] insert cartId into order table 
  - [x] then make another request to get order information with newly created orderId and rest of the info
    - [x] join cookies, cartItems and order table to get all the information and send it as a response
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
### ⚡ Client Tasks
- [x] Create a component for the confirmation page 
  - [x] fetch (post request) in componentDidMount
    - [x] grab token, send it via req
    - [x] get response and show the user what they ordered
      - [x] flavors, price, quantity, order number 

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
