### ISSUE TITLE
Feature: User can view all items

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/Delights-by-Daisy#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all items 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a page where user can view all items
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/200404663-4436c2ee-459a-438a-a377-d5b4f0c42068.png)
![image](https://user-images.githubusercontent.com/103452411/200404733-e00d8105-8bcb-462f-b032-303e1b4a8f73.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to show all the items in cookie table
- [x] Update `data.sql` to include all the information of cookies
  - [x] Hard code all the info for all the cookies so they can go into database, for cookie table 

### ☁️ Server Tasks

- [x] Update `server/index.js` to 
  - [x] set up express server
  - [x] receive fetch request as '/cookies/shopAll/', get request 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to populate the whole page
  - [x] Create a component to populate header (Reuse for every page)
    - [x] Make position sticky so it'll stay on top of the screen 
    - [x] <a> for the links above, home, shop, my basket, about me (desktop)
    - [x] <button> for the menu modal (mobile)
  - [x] Create a component to populate footer (Reuse for almost every page)
    - [x] hard code text and logo img
  - [x] Create component ShopAll to populate body 
    - [x] div
      - [x] <a>left aligned button to go back to home
      - [x] right aligned number of items shown
    - [x] div
      - [x] Create component to populate the items from database via map method
        - [x] Fetch all the cookies information from the cookie table via SQL
        - [x] Grab the image, flavor name and price per item
        - [x] mobile 2 per row, desktop 4 per row
    - [x] div (if there are more products to show, load more button)
### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
