### ISSUE TITLE
Feature: User can view a specific item

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/Delights-by-Daisy#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a specific item.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user can view one specific item when they click on the item from the all products page 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
![image](https://user-images.githubusercontent.com/103452411/200405565-80cb8200-38bc-4bc6-8470-6f26d0c3d0e0.png)

![image](https://user-images.githubusercontent.com/103452411/200405369-f1cf881f-4739-436a-963c-3bada4cf0dde.png)

### ☁️ Server Tasks

- [x] Update `server/index.js` to get the one selected item, get request with cookieId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to show the selected item page
  - [x] Fetch the one cookie item data
  - [x] Create a component to show the fetched data
    - [x] Card with name, weight, image, description, price, buttons
      - [x] Left button is for quantity, right button is to add to basket
      - [x] Add to basket button will need to change color for active and selected state
      - [x] Figure out how to make accordion with data
    - [x] Make sure this page is routed from hash route from previous page
### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
