### ISSUE TITLE
Feature: User can add an item into basket

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/Delights-by-Daisy#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add an item into basket
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks add to basket, the item will be added to their basket and the added to basket modal will show up.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/200405955-196933c4-5f4f-4a53-81c1-357e691377dc.png)
![image](https://user-images.githubusercontent.com/103452411/200406050-3b9a693e-e719-4b20-94ca-e59e739c1402.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to POST request '/api/cart'
  - [x] check if request header has token
    - [x] if it doesn't, insert a new cart into the carts table values (default)
      - [x] then sign a token with the new cartId in the payload 
    - [x] otherwise, don't insert a cart, instead verify the token and get the cartId out
  - [x] then, get the cartId from the token or the insert, and insert into the cartItems table
  - [x] send back a response that includes the token (always, for uniformity)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
### ⚡ Client Tasks
- [x] Create a component to show the modal for adding the item to basket
  - [x] Use modal component from React Bootstrap
    - [x] Have to grab the input value from the quantity box and the cookieId and fetch (post request) to database
    - [x] Create 2 buttons
      - [x] Left button should close modal and return back to same cookie page
      - [x] Right button should also close modal but take user to basket page
- [x] Update add to basket button from detail page to hash route correctly for modal pop up 
### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
