### ISSUE TITLE
Feature: User can view basket

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/Delights-by-Daisy#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see all of their added items in their basket.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks go to basket after adding an item, or when they click my basket(desktop) or the shopping bag icon (mobile) they can view this page.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
![image](https://user-images.githubusercontent.com/103452411/200406949-a39c4d9a-2630-4345-9ee4-1d5cd9129150.png)

![image](https://user-images.githubusercontent.com/103452411/200407124-109697d3-b5b6-4755-a0f2-00b2e6c76471.png)

### ☁️ Server Tasks

- [x] Update `server/index.js` to receive a get request to view cart items for the specific token
  - [x] '/myBasket' 
  - [x] get token and verify to the cart Id
  - [x] then use sql to get all the items that match the cart Id
  - [x] join the cartItems table with the cookies table so I can access pictures, flavor names, etc 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to view the basket page
  - [x] Hash route to this page from the go to basket button and shop link on header '#myBasket'
  - [x] map through multiple items to show the same output
  - [x] write separate function renderCookies for the mapping
  - [x] Make a div to show the subtotal information (bottom sticky for mobile, on right side and scroll down together for desktop and tablet)
    - [x] Make button to link to checkout page with Stripe

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
