### ISSUE TITLE
Feature: User can edit the quantity of item in basket

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/Delights-by-Daisy#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit the quantity of each item in their basket
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to use the +/- icons to increment up and down the quantity of item in their basket.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/200407333-8eaa4bda-2be1-464e-8121-da32502a14e0.png)

![image](https://user-images.githubusercontent.com/103452411/200407259-a7da96dd-eb36-4633-a57c-3b47a74282d8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to patch request
  - [x] sql, update quantity of item
  - [x] where cookieId = $1
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update component to do a fetch request
  - [x] patch request
  - [x] hold the quantity of that cookieId in state
  - [x] event.target.value has to be that specific cookie's quantity 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
