### ISSUE TITLE
Feature: User can remove item in basket

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/Delights-by-Daisy#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove item(s) from their basket
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to remove items in their basket by clicking the remove link.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/103452411/200407725-3252a224-ae26-4a95-a023-b5e8c394dbc0.png)
![image](https://user-images.githubusercontent.com/103452411/200407805-944ed2a0-26f9-4ebd-88b6-674c6b5b42e1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to remove an item from database
  - [x] delete request, find data with cookieId and cartId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update component to send fetch request on an <a> Remove </a>
  - [x] delete method, send over the cookieId and cartId to identify
  - [x] once successful, setState, so the page re-renders with new data

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
