### ISSUE TITLE
Feature: User can place an order

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/Delights-by-Daisy#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can place an order and pay for it.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to check out and pay for their order by clicking proceed to checkout. This will take them to the checkout page populated by Stripe API and take their payments safely.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/200408103-a50cc8cd-c97a-4cf2-9e80-28e431eb3d2a.png)

![image](https://user-images.githubusercontent.com/103452411/200408020-87b44399-d786-42da-a8b6-312d9d9fd22d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to work together with Stripe API
  - [x] Copy and paste stripe code, but integrate with mine so it doesn't break 
  - [x] Find where to implement the necessary details to make it flow with same color theme
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to house the stripe api given code 
  - [x] Component for their main Stripe page
    - [x] Another component for the CheckoutForm function
    - [x] Place the css file in public directory and link properly 
  - [x] Make sure it re-directs to confirmation payment page (hash route)

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
