### ISSUE TITLE
Feature: User can opt to receive a confirmation email

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/Delights-by-Daisy#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can opt to receive an order confirmation email.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the confirmation page loads, there will be a form input where the user can input their email and click send for a confirmation email. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/200408570-b10f77d4-9d7c-41af-b4e6-3f3615fcc2ca.png)
![image](https://user-images.githubusercontent.com/103452411/200408644-3817ce2e-8590-406a-a8f3-a4f402256ea1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks
- [x] Update `schema.sql` to have a column in cartItems to hold req.query (payment intent from stripe) as reference number for payment 
### ☁️ Server Tasks
- [x] Update `server/index.js` to post request 
  - [x] insert email address into orders table with the matching orderId 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
### ⚡ Client Tasks
- [x] Update ConfirmationPage component to have a form input box for email address
  - [x] input box
  - [x] send email button 
    - [x] fetch request (post request, 
    - [x] need to grab orderId from state from previous fetch (edit it to store in state)
      - [x] When this is successful, show a successful message below the input box and disappear after a few seconds 
      - [x] Show an error message if the email address is incorrect.
    - [x] Integrate with SendGrid so it actually sends the email 
      - [x] Figure out how to do this (need to update after reading docs)
### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
